apiVersion: v1
kind: Pod
metadata:
  name: yaaahh-pod  # You can change the pod name if needed
  labels:
    app: yaaahh
spec:
  containers:
  - name: anynamethatIwant
    image: ayrozdzn/tp_devops:v1.0.0
    ports:
    - containerPort: 5000  # The port that the container will listen on
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
